#!/usr/bin/env python3
"""Verify the shared files against SHARED.lock.

The whole point of this repo is that header, footer, tokens and the
registration dialog are the same in every campaign. That is a claim, and a
claim nobody checks is how the last two landings ended up with two token
systems, two modals, two i18n models and four oranges -- both repos documented
their reasoning beautifully and diverged anyway.

So the shared set is hashed, and the hashes are committed. A campaign clone
that has edited one of these files fails CI with the diff command printed.

A campaign that genuinely needs a change to a shared file makes it IN THE
TEMPLATE, bumps SHARED.lock there, and pulls it down. Fixing it in the clone
is the exact move that produced the divergence.

Run:
    python tools/drift.py             # verify (exit 1 on any mismatch)
    python tools/drift.py --write     # regenerate SHARED.lock. TEMPLATE ONLY.
"""

import hashlib
import sys
from pathlib import Path

# Windows consoles still default to cp1252, and these tools report Ukrainian
# and Russian copy back to the user. Without this the report itself crashes on
# the first Cyrillic character -- which turns a real finding into a traceback.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "SHARED.lock"

# Everything a campaign must not touch. index.html is not here: a campaign
# owns its <main> block. The mount-point contract inside it is checked by
# tools/smoke.py instead, which can see whether the shell actually mounted.
SHARED = [
    "css/reset.css",
    "css/tokens.css",
    "css/shell.css",
    "css/form.css",
    "css/stage.css",
    "css/fold.css",
    "js/strings.js",
    "js/i18n.js",
    "js/form.js",
    "js/audio.js",
    "js/shell.js",
    "tools/drift.py",
    "tools/tokens.py",
    "tools/smoke.py",
    "tools/fonts.py",
    ".github/workflows/pages.yml",
]

# tools/optimize.py is deliberately NOT in that list. The four guards define
# what "correct" means and must be identical everywhere; the asset converter is
# a convenience, and a campaign with unusual art is expected to extend it.


def digest(path: Path) -> str:
    # Newline-normalised, so a clone checked out with CRLF is not reported as
    # drift. .gitattributes asks for LF, but a zip download does not read it.
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def current() -> dict:
    out = {}
    for rel in SHARED:
        path = ROOT / rel
        out[rel] = digest(path) if path.is_file() else None
    return out


def write_lock() -> int:
    lines = [
        "# Hashes of the files a campaign must not edit. Verified by",
        "# `python tools/drift.py`; regenerated by `--write` IN THE TEMPLATE ONLY.",
        "# A campaign clone that regenerates this file has silenced the alarm",
        "# rather than answered it.",
        "",
    ]
    missing = []
    for rel, sha in current().items():
        if sha is None:
            missing.append(rel)
            continue
        lines.append(f"{sha}  {rel}")
    LOCK.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    print(f"drift: wrote {LOCK.name} with {len(current()) - len(missing)} entries")
    if missing:
        print("drift: not present, left out of the lock:")
        for rel in missing:
            print(f"  {rel}")
    return 0


def verify() -> int:
    if not LOCK.is_file():
        print("drift: SHARED.lock is missing. In the template, run:", file=sys.stderr)
        print("  python tools/drift.py --write", file=sys.stderr)
        return 1

    expected = {}
    for line in LOCK.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        sha, _, rel = line.partition("  ")
        expected[rel] = sha

    now = current()
    changed, gone = [], []
    for rel, sha in expected.items():
        if now.get(rel) is None:
            gone.append(rel)
        elif now[rel] != sha:
            changed.append(rel)

    if not changed and not gone:
        print(f"drift: {len(expected)} shared file(s) match SHARED.lock")
        return 0

    print(f"drift: {len(changed) + len(gone)} shared file(s) differ from the template\n")
    for rel in gone:
        print(f"  MISSING  {rel}")
    for rel in changed:
        print(f"  CHANGED  {rel}")
    print(
        "\nThese files are the template. A campaign that needs one of them changed\n"
        "changes it in tw-lp-template, bumps SHARED.lock there, and pulls it down --\n"
        "fixing it here is how two landings ended up with four different oranges.\n"
        "\nTo see what moved, against a checkout of the template:\n"
        "  git diff --no-index <template>/css/tokens.css css/tokens.css"
    )
    return 1


def main() -> int:
    return write_lock() if "--write" in sys.argv[1:] else verify()


if __name__ == "__main__":
    sys.exit(main())
